import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Flower Shop App",
  description: "Generated by Kimia Khoshnood",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html>
      <head>
        <title>Flower Shop</title>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
