import { Footer, Header } from "@/components/headerAndFooter";
import ContextProviderLayout from "@/context/context";
import { getDictionary } from "@/dictionaries/dictionaries";
import { LanguageProvider } from "@/providers/LanguageProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Flower Shop App",
  description: "Generated by Kimia Khoshnood",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>
}>) {

  const resolvedParams = await params
  const dictionary = await getDictionary(resolvedParams.lang)

  return (
    <html lang={resolvedParams.lang} dir={resolvedParams.lang === 'fa' ? 'rtl' : 'ltr'}>
      <head>
        <title>Flower Shop</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><div className="!min-h-screen flex flex-col">
          <ContextProviderLayout>
            <LanguageProvider dictionary={dictionary} lang={resolvedParams.lang}>
              <Header />
              <div className="flex-1 h-full grow-1">{children}</div>
              <hr className="text-gray-300 w-full" />
              <Footer />
            </LanguageProvider>
          </ContextProviderLayout>
        </div>
      </body>
    </html>
  );
}
