import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Footer, Header} from "@/components/headerAndFooter";
import ContextProviderLayout from "@/context/context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Flower Shop App",
  description: "Generated by Kimia Khoshnood",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ContextProviderLayout>
        <Header/>
        {children}
        <hr className="text-gray-300 w-full"/>
        <Footer/>
        </ContextProviderLayout>
      </body>
    </html>
  );
}
